steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/pew-search/resume', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/pew-search/resume']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'resume', '--image', 'gcr.io/pew-search/resume', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
